// <auto-generated />
namespace TopStoreApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditOrderData1Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditOrderData1Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202208211609564_EditOrderData1Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
